name: SAE Checker

on:
  schedule:
    - cron: "*/3 * * * *"          # каждые 3 минуты (UTC)
  workflow_dispatch: {}             # ручной запуск

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -euo pipefail
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      - name: Run checker (one-shot) and append to daily log
        id: run_checker
        run: |
          set -euo pipefail
          mkdir -p logs
          LOG="logs/$(date -u +%F).log"   # один файл на день (UTC)
          RUN_OUT="run.out"
          {
            echo "===== RUN $(date -u '+%Y-%m-%d %H:%M:%S UTC') ====="
            python checker.py
            echo
          } | tee -a "$LOG" | tee "$RUN_OUT" >/dev/null

      - name: Send log text to Telegram (chunked)
        if: always()
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          set -euo pipefail
          if [ -z "${BOT_TOKEN:-}" ] || [ -z "${CHAT_ID:-}" ]; then
            echo "Telegram secrets not set, skipping."
            exit 0
          fi

          # Разбиваем run.out на части <= 3500 символов и сохраняем во временные файлы
          rm -f chunk_*.txt || true
          python -c "import sys, pathlib
from pathlib import Path
p = Path('run.out')
text = p.read_text(encoding='utf-8', errors='replace') if p.exists() else ''
MAX = 3500
chunks = [text[i:i+MAX] for i in range(0, len(text), MAX)] or ['(empty)']
n = len(chunks)
for i, ch in enumerate(chunks, 1):
    prefix = f'[{i}/{n}] ' if n > 1 else ''
    Path(f'chunk_{i:03}.txt').write_text(prefix + ch, encoding='utf-8')
"

          # Шлём каждый кусок как обычное сообщение
          shopt -s nullglob
          for f in chunk_*.txt; do
            curl -sS "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
              --data-urlencode "chat_id=${CHAT_ID}" \
              --data-urlencode "text@${f}" \
              --data "disable_web_page_preview=true" \
              >/dev/null || echo "Telegram send failed for $f"
          done

      - name: Commit & push logs
        if: always()   # даже если предыдущий шаг упал — всё равно пушим то, что успели записать
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f logs/*.log || true
          git commit -m "Append log: $(date -u '+%F %T UTC') [skip ci]" || echo "No changes to commit"
          git push
