name: SAE Checker

on:
  schedule:
    - cron: "*/30 * * * *"  # каждые 30 минут (UTC)
  workflow_dispatch: {}      # плюс ручной запуск по кнопке

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run checker
        run: python checker.py
