name: SAE Checker
on:
  schedule:
    - cron: "*/30 * * * *"   # каждые 30 минут (UTC)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: sae-checker
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - name: Run checker
        run: python checker.py
