name: SAE Checker

on:
  schedule:
    - cron: "*/2 * * * *"          # каждые 3 минуты (UTC)
  workflow_dispatch: {}             # ручной запуск

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -euo pipefail
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      - name: Run checker (one-shot) and append to daily log
        id: run_checker
        run: |
          set -euo pipefail
          mkdir -p logs
          LOG="logs/$(date -u +%F).log"   # один файл на день (UTC)
          RUN_OUT="run.out"
          {
            echo "===== RUN $(date -u '+%Y-%m-%d %H:%M:%S UTC') ====="
            python checker.py
            echo
          } | tee -a "$LOG" | tee "$RUN_OUT" >/dev/null

      - name: Send run.out to Telegram
        if: always()
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          set -euo pipefail
          if [ -z "${BOT_TOKEN:-}" ] || [ -z "${CHAT_ID:-}" ]; then
            echo "Telegram secrets not set, skipping."
            exit 0
          fi
          CAPTION="SAE checker log ($(date -u '+%Y-%m-%d %H:%M:%S UTC'))"
          curl -sS -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument" \
            -F chat_id="${CHAT_ID}" \
            -F caption="${CAPTION}" \
            -F document=@run.out >/dev/null || echo "Telegram send failed"

      - name: Commit & push logs
        if: always()
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f logs/*.log || true
          git commit -m "Append log: $(date -u '+%F %T UTC') [skip ci]" || echo "No changes to commit"
          git push
