name: SAE Checker

on:
  schedule:
    - cron: "*/3 * * * *"          # каждые 3 минуты (UTC)
  workflow_dispatch: {}             # ручной запуск

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -euo pipefail
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      - name: Run checker (one-shot)
        run: |
          set -euo pipefail
          python checker.py
