name: SAE Checker

on:
  schedule:
    - cron: "*/3 * * * *"          # каждые 3 минуты (UTC)
  workflow_dispatch: {}             # ручной запуск

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -euo pipefail
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests
          fi

      - name: Run checker (one-shot) and append to daily log
        run: |
          set -euo pipefail
          mkdir -p logs
          LOG="logs/$(date -u +%F).log"   # один файл на день (UTC)
          {
            echo "===== RUN $(date -u '+%Y-%m-%d %H:%M:%S UTC') ====="
            python checker.py
            echo
          } | tee -a "$LOG"

      - name: Commit & push logs
        if: always()   # даже если предыдущий шаг упал — всё равно пушим то, что успели записать
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f logs/*.log || true
          git commit -m "Append log: $(date -u '+%F %T UTC') [skip ci]" || echo "No changes to commit"
          git push
